# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170301_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='page-slug'),
        ),
    ]
