# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170303_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='leave_capture',
            field=models.BooleanField(default=True),
        ),
    ]
